export const categories = [
  {
    category_id: "mobile",
    category_name: "Mobile",
    category_image: "https://images.pexels.com/photos/9667336/pexels-photo-9667336.jpeg",
    category_types: ["nav", "top_category"],
  },
  {
    category_id: "tablet",
    category_name: "Tablet",
    category_image: "https://images.pexels.com/photos/33632618/pexels-photo-33632618.jpeg",
    category_types: ["nav", "top_category"],
  },
  {
    category_id: "laptop",
    category_name: "Laptop",
    category_image: "https://images.pexels.com/photos/34130516/pexels-photo-34130516.jpeg",
    category_types: ["nav", "top_category"],
  },
  {
    category_id: "desktop",
    category_name: "Desktop",
    category_image: "https://images.pexels.com/photos/18024480/pexels-photo-18024480.jpeg",
    category_types: ["nav"],
  },
  {
    category_id: "smartwatch",
    category_name: "Smartwatch",
    category_image: "https://images.pexels.com/photos/11483999/pexels-photo-11483999.jpeg",
    category_types: ["nav", "top_category"],
  },
  {
    category_id: "headphones",
    category_name: "Headphones",
    category_image: "https://images.pexels.com/photos/3945667/pexels-photo-3945667.jpeg",
    category_types: [],
  },
  {
    category_id: "earbuds",
    category_name: "Earbuds",
    category_image: "https://images.pexels.com/photos/3921817/pexels-photo-3921817.jpeg",
    category_types: ["nav", "top_category"],
  },
  {
    category_id: "accessories",
    category_name: "Accessories",
    category_image: "https://images.pexels.com/photos/27095031/pexels-photo-27095031.jpeg",
    category_types: ["nav"],
  },
  {
    category_id: "television",
    category_name: "Television",
    category_image: "https://images.pexels.com/photos/37834298/pexels-photo-37834298.jpeg",
    category_types: ["nav", "top_category"],
  },
  {
    category_id: "cameras",
    category_name: "Cameras",
    category_image: "https://images.pexels.com/photos/17733586/pexels-photo-17733586.jpeg",
    category_types: ["nav", "top_category"],
  },
  {
    category_id: "speakers",
    category_name: "Speakers",
    category_image: "https://images.pexels.com/photos/14309806/pexels-photo-14309806.jpeg",
    category_types: ["nav"],
  },
  {
    category_id: "cctv",
    category_name: "CCTV",
    category_image: "https://images.pexels.com/photos/29291981/pexels-photo-29291981.jpeg",
    category_types: ["nav", "top_category"],
  },
  {
    category_id: "gaming",
    category_name: "Gaming",
    category_image: "https://images.pexels.com/photos/12718979/pexels-photo-12718979.jpeg",
    category_types: ["top_category"],
  },
  {
    category_id: "monitors",
    category_name: "Monitors",
    category_image: "https://images.pexels.com/photos/11288109/pexels-photo-11288109.jpeg",
    category_types: [],
  },
  {
    category_id: "keyboards",
    category_name: "Keyboards",
    category_image: "https://images.pexels.com/photos/7531569/pexels-photo-7531569.jpeg",
    category_types: [],
  },
  {
    category_id: "mouse",
    category_name: "Mouse",
    category_image: "https://images.pexels.com/photos/7643947/pexels-photo-7643947.jpeg",
    category_types: [],
  },
  {
    category_id: "storage",
    category_name: "Storage",
    category_image: "https://images.pexels.com/photos/5882576/pexels-photo-5882576.jpeg",
    category_types: [],
  },
];

export const products = {
  
}

export const laptops = [
  {
    id: "686f8d9b7a2c4e1f3b5d9b01",
    brand: "Apple",
    name: 'MacBook Air 13" M4',
    price: 114900,
    originalPrice: 119900,
    discount: 4,
    rating: 4.9,
    reviews: 2431,
    ram: "16GB",
    storage: "512GB SSD",
    processor: "Apple M4",
    display: '13.6" Liquid Retina',
    image: "/images/products/macbook-air-m4.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b02",
    brand: "Apple",
    name: 'MacBook Pro 14" M4 Pro',
    price: 199900,
    originalPrice: 209900,
    discount: 5,
    rating: 4.9,
    reviews: 1804,
    ram: "24GB",
    storage: "1TB SSD",
    processor: "Apple M4 Pro",
    display: '14.2" Liquid Retina XDR',
    image: "/images/products/macbook-pro-m4-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b03",
    brand: "Dell",
    name: "XPS 13",
    price: 149999,
    originalPrice: 159999,
    discount: 6,
    rating: 4.8,
    reviews: 1125,
    ram: "16GB",
    storage: "512GB SSD",
    processor: "Intel Core Ultra 7",
    display: '13.4" OLED',
    image: "/images/products/dell-xps-13.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b04",
    brand: "Dell",
    name: "Alienware m18 R2",
    price: 289999,
    originalPrice: 309999,
    discount: 6,
    rating: 4.8,
    reviews: 512,
    ram: "32GB",
    storage: "1TB SSD",
    processor: "Intel Core i9",
    display: '18" QHD+ 165Hz',
    image: "/images/products/alienware-m18-r2.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b05",
    brand: "HP",
    name: "Spectre x360 14",
    price: 159999,
    originalPrice: 169999,
    discount: 6,
    rating: 4.7,
    reviews: 963,
    ram: "16GB",
    storage: "1TB SSD",
    processor: "Intel Core Ultra 7",
    display: '14" OLED Touch',
    image: "/images/products/hp-spectre-x360.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b06",
    brand: "HP",
    name: "Victus 16",
    price: 89999,
    originalPrice: 99999,
    discount: 10,
    rating: 4.6,
    reviews: 1531,
    ram: "16GB",
    storage: "512GB SSD",
    processor: "AMD Ryzen 7",
    display: '16.1" FHD 144Hz',
    image: "/images/products/hp-victus-16.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b07",
    brand: "Lenovo",
    name: "ThinkPad X1 Carbon Gen 13",
    price: 189999,
    originalPrice: 199999,
    discount: 5,
    rating: 4.9,
    reviews: 1102,
    ram: "32GB",
    storage: "1TB SSD",
    processor: "Intel Core Ultra 7",
    display: '14" OLED',
    image: "/images/products/thinkpad-x1-carbon.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b08",
    brand: "Lenovo",
    name: "Legion Pro 7i",
    price: 239999,
    originalPrice: 254999,
    discount: 6,
    rating: 4.8,
    reviews: 845,
    ram: "32GB",
    storage: "1TB SSD",
    processor: "Intel Core i9",
    display: '16" QHD+ 240Hz',
    image: "/images/products/legion-pro-7i.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b09",
    brand: "ASUS",
    name: "ROG Zephyrus G16",
    price: 219999,
    originalPrice: 229999,
    discount: 4,
    rating: 4.8,
    reviews: 934,
    ram: "32GB",
    storage: "1TB SSD",
    processor: "Intel Core Ultra 9",
    display: '16" OLED 240Hz',
    image: "/images/products/rog-zephyrus-g16.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b0a",
    brand: "ASUS",
    name: "Zenbook 14 OLED",
    price: 99999,
    originalPrice: 109999,
    discount: 9,
    rating: 4.7,
    reviews: 1206,
    ram: "16GB",
    storage: "512GB SSD",
    processor: "Intel Core Ultra 5",
    display: '14" OLED',
    image: "/images/products/zenbook-14-oled.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b0b",
    brand: "Acer",
    name: "Predator Helios Neo 16",
    price: 134999,
    originalPrice: 144999,
    discount: 7,
    rating: 4.6,
    reviews: 902,
    ram: "16GB",
    storage: "1TB SSD",
    processor: "Intel Core i7",
    display: '16" QHD 165Hz',
    image: "/images/products/predator-helios-neo-16.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b0c",
    brand: "MSI",
    name: "Stealth 16 AI Studio",
    price: 249999,
    originalPrice: 259999,
    discount: 4,
    rating: 4.7,
    reviews: 621,
    ram: "32GB",
    storage: "1TB SSD",
    processor: "Intel Core Ultra 9",
    display: '16" UHD+ OLED',
    image: "/images/products/msi-stealth-16-ai.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b0d",
    brand: "Samsung",
    name: "Galaxy Book5 Pro",
    price: 154999,
    originalPrice: 164999,
    discount: 6,
    rating: 4.7,
    reviews: 543,
    ram: "16GB",
    storage: "1TB SSD",
    processor: "Intel Core Ultra 7",
    display: '16" AMOLED',
    image: "/images/products/galaxy-book5-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b0e",
    brand: "Microsoft",
    name: "Surface Laptop 7",
    price: 139999,
    originalPrice: 149999,
    discount: 7,
    rating: 4.8,
    reviews: 736,
    ram: "16GB",
    storage: "512GB SSD",
    processor: "Snapdragon X Elite",
    display: '15" PixelSense',
    image: "/images/products/surface-laptop-7.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9b0f",
    brand: "LG",
    name: "Gram 16",
    price: 129999,
    originalPrice: 139999,
    discount: 7,
    rating: 4.8,
    reviews: 481,
    ram: "16GB",
    storage: "1TB SSD",
    processor: "Intel Core Ultra 7",
    display: '16" WQXGA IPS',
    image: "/images/products/lg-gram-16.png",
  },
];

export const computerAccessories = [
  {
    id: "686f8d9b7a2c4e1f3b5d9c01",
    brand: "Logitech",
    name: "MX Master 3S Wireless Mouse",
    price: 8995,
    originalPrice: 10995,
    discount: 18,
    rating: 4.9,
    reviews: 3245,
    category: "Mouse",
    color: "Graphite",
    connectivity: "Bluetooth + USB Receiver",
    image: "/images/products/logitech-mx-master-3s.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c02",
    brand: "Logitech",
    name: "MX Keys S Wireless Keyboard",
    price: 10995,
    originalPrice: 12995,
    discount: 15,
    rating: 4.8,
    reviews: 1842,
    category: "Keyboard",
    connectivity: "Bluetooth",
    image: "/images/products/logitech-mx-keys-s.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c03",
    brand: "Keychron",
    name: "K2 Pro Mechanical Keyboard",
    price: 8999,
    originalPrice: 9999,
    discount: 10,
    rating: 4.8,
    reviews: 1354,
    category: "Keyboard",
    connectivity: "Bluetooth/Wired",
    image: "/images/products/keychron-k2-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c04",
    brand: "Razer",
    name: "DeathAdder V3 Pro",
    price: 10999,
    originalPrice: 12999,
    discount: 15,
    rating: 4.8,
    reviews: 1288,
    category: "Gaming Mouse",
    connectivity: "Wireless",
    image: "/images/products/razer-deathadder-v3-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c05",
    brand: "HyperX",
    name: "Cloud III Gaming Headset",
    price: 7999,
    originalPrice: 9999,
    discount: 20,
    rating: 4.7,
    reviews: 964,
    category: "Headset",
    connectivity: "USB-C / 3.5mm",
    image: "/images/products/hyperx-cloud-3.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c06",
    brand: "Logitech",
    name: "C920 HD Pro Webcam",
    price: 6499,
    originalPrice: 7999,
    discount: 19,
    rating: 4.7,
    reviews: 4512,
    category: "Webcam",
    connectivity: "USB",
    image: "/images/products/logitech-c920.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c07",
    brand: "TP-Link",
    name: "USB Wi-Fi Adapter Archer T3U",
    price: 1799,
    originalPrice: 2299,
    discount: 22,
    rating: 4.6,
    reviews: 2187,
    category: "Network Adapter",
    connectivity: "USB 3.0",
    image: "/images/products/tplink-archer-t3u.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c08",
    brand: "Samsung",
    name: "T7 Portable SSD 1TB",
    price: 8499,
    originalPrice: 9999,
    discount: 15,
    rating: 4.9,
    reviews: 3644,
    category: "External SSD",
    storage: "1TB",
    image: "/images/products/samsung-t7-1tb.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c09",
    brand: "SanDisk",
    name: "Ultra Dual Drive Luxe 256GB",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    rating: 4.7,
    reviews: 2156,
    category: "USB Drive",
    storage: "256GB",
    image: "/images/products/sandisk-dual-drive-luxe.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c0a",
    brand: "Seagate",
    name: "Expansion Portable HDD 2TB",
    price: 5999,
    originalPrice: 6999,
    discount: 14,
    rating: 4.6,
    reviews: 4231,
    category: "External HDD",
    storage: "2TB",
    image: "/images/products/seagate-expansion-2tb.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c0b",
    brand: "Anker",
    name: "8-in-1 USB-C Hub",
    price: 4499,
    originalPrice: 5499,
    discount: 18,
    rating: 4.8,
    reviews: 1597,
    category: "USB Hub",
    image: "/images/products/anker-usbc-hub.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c0c",
    brand: "Belkin",
    name: "USB-C to HDMI Adapter",
    price: 1999,
    originalPrice: 2499,
    discount: 20,
    rating: 4.6,
    reviews: 842,
    category: "Adapter",
    image: "/images/products/belkin-usbc-hdmi.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c0d",
    brand: "Cooler Master",
    name: "Notepal X150R Laptop Cooling Pad",
    price: 2999,
    originalPrice: 3499,
    discount: 14,
    rating: 4.5,
    reviews: 698,
    category: "Cooling Pad",
    image: "/images/products/cooler-master-x150r.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c0e",
    brand: "APC",
    name: "600VA UPS Battery Backup",
    price: 3899,
    originalPrice: 4499,
    discount: 13,
    rating: 4.7,
    reviews: 1941,
    category: "UPS",
    image: "/images/products/apc-600va-ups.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9c0f",
    brand: "Amazon Basics",
    name: "XL Extended Mouse Pad",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.5,
    reviews: 2845,
    category: "Mouse Pad",
    image: "/images/products/amazonbasics-mousepad-xl.png",
  },
];

export const smartphones = [
  {
    id: "686f8d9b7a2c4e1f3b5d9a01",
    brand: "Apple",
    name: "iPhone 16",
    price: 79999,
    originalPrice: 84999,
    discount: 6,
    rating: 4.8,
    reviews: 2456,
    storage: "128GB",
    ram: "8GB",
    color: "Black",
    image: "/images/products/iphone-16-black.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a02",
    brand: "Apple",
    name: "iPhone 16 Pro",
    price: 119999,
    originalPrice: 129999,
    discount: 8,
    rating: 4.9,
    reviews: 1894,
    storage: "256GB",
    ram: "8GB",
    color: "Natural Titanium",
    image: "/images/products/iphone-16-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a03",
    brand: "Samsung",
    name: "Galaxy S25",
    price: 74999,
    originalPrice: 82999,
    discount: 10,
    rating: 4.8,
    reviews: 1520,
    storage: "256GB",
    ram: "12GB",
    color: "Silver Shadow",
    image: "/images/products/galaxy-s25.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a04",
    brand: "Samsung",
    name: "Galaxy S25 Ultra",
    price: 129999,
    originalPrice: 139999,
    discount: 7,
    rating: 4.9,
    reviews: 2311,
    storage: "512GB",
    ram: "12GB",
    color: "Titanium Gray",
    image: "/images/products/galaxy-s25-ultra.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a05",
    brand: "Google",
    name: "Pixel 9",
    price: 69999,
    originalPrice: 74999,
    discount: 7,
    rating: 4.8,
    reviews: 945,
    storage: "128GB",
    ram: "12GB",
    color: "Obsidian",
    image: "/images/products/pixel-9.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a06",
    brand: "Google",
    name: "Pixel 9 Pro",
    price: 109999,
    originalPrice: 114999,
    discount: 4,
    rating: 4.9,
    reviews: 703,
    storage: "256GB",
    ram: "16GB",
    color: "Porcelain",
    image: "/images/products/pixel-9-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a07",
    brand: "OnePlus",
    name: "OnePlus 13",
    price: 64999,
    originalPrice: 69999,
    discount: 7,
    rating: 4.7,
    reviews: 1310,
    storage: "256GB",
    ram: "12GB",
    color: "Black Eclipse",
    image: "/images/products/oneplus-13.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a08",
    brand: "Nothing",
    name: "Nothing Phone (3)",
    price: 54999,
    originalPrice: 59999,
    discount: 8,
    rating: 4.6,
    reviews: 842,
    storage: "256GB",
    ram: "12GB",
    color: "White",
    image: "/images/products/nothing-phone-3.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a09",
    brand: "Xiaomi",
    name: "Xiaomi 15",
    price: 59999,
    originalPrice: 64999,
    discount: 8,
    rating: 4.6,
    reviews: 987,
    storage: "256GB",
    ram: "12GB",
    color: "White",
    image: "/images/products/xiaomi-15.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a0a",
    brand: "Xiaomi",
    name: "Xiaomi 15 Ultra",
    price: 99999,
    originalPrice: 109999,
    discount: 9,
    rating: 4.9,
    reviews: 552,
    storage: "512GB",
    ram: "16GB",
    color: "Black",
    image: "/images/products/xiaomi-15-ultra.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a0b",
    brand: "Motorola",
    name: "Edge 60 Pro",
    price: 37999,
    originalPrice: 42999,
    discount: 12,
    rating: 4.5,
    reviews: 684,
    storage: "256GB",
    ram: "12GB",
    color: "Blue",
    image: "/images/products/moto-edge-60-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a0c",
    brand: "iQOO",
    name: "iQOO 13",
    price: 54999,
    originalPrice: 59999,
    discount: 8,
    rating: 4.7,
    reviews: 876,
    storage: "256GB",
    ram: "12GB",
    color: "Legend",
    image: "/images/products/iqoo-13.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a0d",
    brand: "Realme",
    name: "GT 7 Pro",
    price: 49999,
    originalPrice: 54999,
    discount: 9,
    rating: 4.6,
    reviews: 1034,
    storage: "256GB",
    ram: "12GB",
    color: "Mars Orange",
    image: "/images/products/realme-gt-7-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a0e",
    brand: "OPPO",
    name: "Find X8 Pro",
    price: 89999,
    originalPrice: 94999,
    discount: 5,
    rating: 4.8,
    reviews: 611,
    storage: "512GB",
    ram: "16GB",
    color: "Space Black",
    image: "/images/products/oppo-find-x8-pro.png",
  },
  {
    id: "686f8d9b7a2c4e1f3b5d9a0f",
    brand: "vivo",
    name: "X200 Pro",
    price: 94999,
    originalPrice: 99999,
    discount: 5,
    rating: 4.8,
    reviews: 728,
    storage: "512GB",
    ram: "16GB",
    color: "Titanium",
    image: "/images/products/vivo-x200-pro.png",
  },
];


export const topBrands = [
  {
    name: "IPHONE",
    subtitle: "UP to 80% OFF",
    image:
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&h=250&fit=crop",
    bg: "bg-gradient-to-br from-gray-100 to-gray-200",
  },
  {
    name: "realme",
    subtitle: "UP to 80% OFF",
    image:
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=250&fit=crop",
    bg: "bg-gradient-to-br from-yellow-50 to-yellow-100",
  },
  {
    name: "XIAOMI",
    subtitle: "UP to 80% OFF",
    image:
      "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&h=250&fit=crop",
    bg: "bg-gradient-to-br from-orange-50 to-orange-100",
  },
];


export const heroSlides = [
  {
    id: 1,
    tagline: "Best Deal Online on smart watches",
    title: "SMART WEARABLE.",
    subtitle: "UP to 80% OFF",
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=400&fit=crop",
  },
  {
    id: 2,
    tagline: "Best Deal Online on smartphones",
    title: "LATEST PHONES.",
    subtitle: "UP to 60% OFF",
    image:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&h=400&fit=crop",
  },
  {
    id: 3,
    tagline: "Best Deal Online on electronics",
    title: "TOP GADGETS.",
    subtitle: "UP to 70% OFF",
    image:
      "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500&h=400&fit=crop",
  },
];

export function formatPrice(amount: number) {
  return `₹${amount.toLocaleString("en-IN")}`;
}

export type CategoryProduct = {
  id: string;
  brand: string;
  name: string;
  price: number;
  originalPrice: number;
  discount: number;
  rating: number;
  reviews: number;
  image: string;
};

export type CategoryOffer = {
  id: string;
  eventLabel: string;
  title: string;
  price: number;
  originalPrice: number;
  tagline: string;
  emiAmount: number;
  rating: number;
  image: string;
  bg: string;
};

export type CategoryBrand = {
  id: string;
  name: string;
  image: string;
};

const categoryOffersMap: Record<string, CategoryOffer[]> = {
  mobile: [
    {
      id: "offer-1",
      eventLabel: "Mobiles MAHOTSAV",
      title: "POVA Curve 2 5G",
      price: 28499,
      originalPrice: 31999,
      tagline: "World's Slimmest 8000mAh Curve Dis.",
      emiAmount: 4750,
      rating: 4.3,
      image:
        "https://rukminim1.flixcart.com/image/312/312/xif0q/mobile/3/6/8/-original-imahf6vhzg9tzfzr.jpeg?q=70",
      bg: "from-slate-800 via-slate-700 to-slate-900",
    },
    {
      id: "offer-2",
      eventLabel: "Mobiles MAHOTSAV",
      title: "motorola g96 5G",
      price: 15999,
      originalPrice: 25999,
      tagline: "Segment's Biggest 6000mAh Battery",
      emiAmount: 2667,
      rating: 4.4,
      image:
        "https://rukminim1.flixcart.com/image/312/312/xif0q/mobile/k/2/6/-original-imah8f6yq8q8q8q8.jpeg?q=70",
      bg: "from-rose-900 via-rose-800 to-rose-950",
    },
    {
      id: "offer-3",
      eventLabel: "Mobiles MAHOTSAV",
      title: "Galaxy S25 Ultra 512GB",
      price: 84999,
      originalPrice: 129999,
      tagline: "Galaxy AI is here",
      emiAmount: 14167,
      rating: 4.6,
      image:
        "https://rukminim1.flixcart.com/image/312/312/xif0q/mobile/5/4/3/-original-imah8yq8q8q8q8q8.jpeg?q=70",
      bg: "from-indigo-950 via-indigo-900 to-slate-900",
    },
  ],
  laptop: [
    {
      id: "laptop-offer-1",
      eventLabel: "Laptop Fest",
      title: "MacBook Air M4",
      price: 114900,
      originalPrice: 119900,
      tagline: "Supercharged by Apple M4 chip",
      emiAmount: 9583,
      rating: 4.9,
      image: "/images/products/macbook-air-m4.png",
      bg: "from-gray-800 via-gray-700 to-gray-900",
    },
    {
      id: "laptop-offer-2",
      eventLabel: "Laptop Fest",
      title: "ROG Zephyrus G16",
      price: 219999,
      originalPrice: 229999,
      tagline: "Gaming powerhouse with OLED display",
      emiAmount: 18333,
      rating: 4.8,
      image: "/images/products/rog-zephyrus-g16.png",
      bg: "from-zinc-900 via-zinc-800 to-black",
    },
  ],
};

const categoryBrandsMap: Record<string, CategoryBrand[]> = {
  mobile: [
    { id: "iphone", name: "iPhone", image: "/images/products/iphone-16-black.png" },
    { id: "iqoo", name: "iQOO", image: "/images/products/iqoo-13.png" },
    { id: "samsung", name: "Samsung", image: "/images/products/galaxy-s25.png" },
    { id: "motorola", name: "motorola", image: "/images/products/moto-edge-60-pro.png" },
    { id: "google", name: "Google", image: "/images/products/pixel-9.png" },
    { id: "vivo", name: "vivo", image: "/images/products/vivo-x200-pro.png" },
    { id: "oppo", name: "OPPO", image: "/images/products/oppo-find-x8-pro.png" },
    { id: "xiaomi", name: "POCO", image: "/images/products/xiaomi-15.png" },
    { id: "realme", name: "realme", image: "/images/products/realme-gt-7-pro.png" },
    { id: "oneplus", name: "OnePlus", image: "/images/products/oneplus-13.png" },
    { id: "nothing", name: "CMF by Nothing", image: "/images/products/nothing-phone-3.png" },
    { id: "samsung-s", name: "Samsung Galaxy S series", image: "/images/products/galaxy-s25-ultra.png" },
    { id: "honor", name: "HONOR", image: "https://images.pexels.com/photos/9667336/pexels-photo-9667336.jpeg" },
    { id: "tecno", name: "Tecno", image: "https://images.pexels.com/photos/1092675/pexels-photo-1092675.jpeg" },
    { id: "infinix", name: "Infinix", image: "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg" },
    { id: "lava", name: "LAVA", image: "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg" },
    { id: "narzo", name: "Realme Narzo", image: "/images/products/realme-gt-7-pro.png" },
    { id: "boltt", name: "boltt", image: "https://images.pexels.com/photos/11483999/pexels-photo-11483999.jpeg" },
  ],
  laptop: [
    { id: "apple", name: "Apple", image: "/images/products/macbook-air-m4.png" },
    { id: "dell", name: "Dell", image: "/images/products/dell-xps-13.png" },
    { id: "hp", name: "HP", image: "/images/products/hp-spectre-x360.png" },
    { id: "lenovo", name: "Lenovo", image: "/images/products/thinkpad-x1-carbon.png" },
    { id: "asus", name: "ASUS", image: "/images/products/zenbook-14-oled.png" },
    { id: "acer", name: "Acer", image: "/images/products/predator-helios-neo-16.png" },
    { id: "msi", name: "MSI", image: "/images/products/msi-stealth-16-ai.png" },
    { id: "samsung", name: "Samsung", image: "/images/products/galaxy-book5-pro.png" },
    { id: "microsoft", name: "Microsoft", image: "/images/products/surface-laptop-7.png" },
    { id: "lg", name: "LG", image: "/images/products/lg-gram-16.png" },
  ],
};

const categoryProductsMap: Record<string, CategoryProduct[]> = {
  mobile: smartphones,
  laptop: laptops,
  accessories: computerAccessories,
};

export function getOffersByCategory(categoryId: string): CategoryOffer[] {
  return categoryOffersMap[categoryId] ?? [];
}

export function getBrandsByCategory(categoryId: string): CategoryBrand[] {
  if (categoryBrandsMap[categoryId]) {
    return categoryBrandsMap[categoryId];
  }

  const products = getProductsByCategory(categoryId);
  const seen = new Set<string>();

  return products.reduce<CategoryBrand[]>((brands, product) => {
    const key = product.brand.toLowerCase();
    if (seen.has(key)) return brands;
    seen.add(key);
    brands.push({
      id: key,
      name: product.brand,
      image: product.image,
    });
    return brands;
  }, []);
}

export function getProductsByCategory(categoryId: string): CategoryProduct[] {
  return categoryProductsMap[categoryId] ?? [];
}

export function getCategoryById(categoryId: string) {
  return categories.find((category) => category.category_id === categoryId);
}
