
export const categories = [
  {
    _id: "687000000000000000000001",
    name: "Mobile",
    slug: "mobile",
    description: "Browse the latest smartphones from top brands.",
    image: "https://images.pexels.com/photos/9667336/pexels-photo-9667336.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000002",
    name: "Tablet",
    slug: "tablet",
    description: "Discover powerful tablets for work and entertainment.",
    image:
      "https://images.pexels.com/photos/33632618/pexels-photo-33632618.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000003",
    name: "Laptop",
    slug: "laptop",
    description: "Shop laptops for gaming, business, and everyday use.",
    image:
      "https://images.pexels.com/photos/34130516/pexels-photo-34130516.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000004",
    name: "Desktop",
    slug: "desktop",
    description: "Explore desktop computers for home and office.",
    image:
      "https://images.pexels.com/photos/18024480/pexels-photo-18024480.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000005",
    name: "Smartwatch",
    slug: "smartwatch",
    description: "Stay connected with premium smartwatches.",
    image:
      "https://images.pexels.com/photos/11483999/pexels-photo-11483999.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000006",
    name: "Headphones",
    slug: "headphones",
    description: "Find wired and wireless headphones for every need.",
    image: "https://images.pexels.com/photos/3945667/pexels-photo-3945667.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000007",
    name: "Earbuds",
    slug: "earbuds",
    description: "Experience true wireless earbuds with immersive sound.",
    image: "https://images.pexels.com/photos/3921817/pexels-photo-3921817.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000008",
    name: "Accessories",
    slug: "accessories",
    description: "Essential accessories for all your devices.",
    image:
      "https://images.pexels.com/photos/27095031/pexels-photo-27095031.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000009",
    name: "Television",
    slug: "television",
    description: "Shop Smart TVs, LED TVs, and entertainment systems.",
    image:
      "https://images.pexels.com/photos/37834298/pexels-photo-37834298.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68700000000000000000000a",
    name: "Cameras",
    slug: "cameras",
    description: "Capture every moment with professional cameras.",
    image:
      "https://images.pexels.com/photos/17733586/pexels-photo-17733586.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68700000000000000000000b",
    name: "Speakers",
    slug: "speakers",
    description: "Portable and home speakers with rich sound.",
    image:
      "https://images.pexels.com/photos/14309806/pexels-photo-14309806.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68700000000000000000000c",
    name: "CCTV",
    slug: "cctv",
    description: "Security cameras and surveillance solutions.",
    image:
      "https://images.pexels.com/photos/29291981/pexels-photo-29291981.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68700000000000000000000d",
    name: "Gaming",
    slug: "gaming",
    description: "Gaming consoles, accessories, and peripherals.",
    image:
      "https://images.pexels.com/photos/12718979/pexels-photo-12718979.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68700000000000000000000e",
    name: "Monitors",
    slug: "monitors",
    description: "High-resolution monitors for work and gaming.",
    image:
      "https://images.pexels.com/photos/11288109/pexels-photo-11288109.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68700000000000000000000f",
    name: "Keyboards",
    slug: "keyboards",
    description: "Mechanical and membrane keyboards for every user.",
    image: "https://images.pexels.com/photos/7531569/pexels-photo-7531569.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000010",
    name: "Mouse",
    slug: "mouse",
    description: "Wireless and gaming mice with precision tracking.",
    image: "https://images.pexels.com/photos/7643947/pexels-photo-7643947.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "687000000000000000000011",
    name: "Storage",
    slug: "storage",
    description: "SSDs, HDDs, memory cards, and external drives.",
    image: "https://images.pexels.com/photos/5882576/pexels-photo-5882576.jpeg",
    parentCategoryId: undefined,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const brands = [
  {
    _id: "688000000000000000000001",
    name: "Apple",
    slug: "apple",
    logo: "https://images.pexels.com/photos/13886741/pexels-photo-13886741.jpeg",
    description: "Premium smartphones, laptops and accessories.",
    productCategories: ["mobile", "laptop", "tablet", "smartwatch", "earbuds", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000002",
    name: "Samsung",
    slug: "samsung",
    logo: "/images/brands/samsung.png",
    description: "Leading manufacturer of consumer electronics.",
    productCategories: ["mobile", "tablet", "smartwatch", "earbuds", "television", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000003",
    name: "Google",
    slug: "google",
    logo: "/images/brands/google.png",
    description: "Google Pixel devices and smart products.",
    productCategories: ["mobile", "earbuds", "smartwatch"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000004",
    name: "OnePlus",
    slug: "oneplus",
    logo: "/images/brands/oneplus.png",
    description: "Flagship Android smartphones.",
    productCategories: ["mobile", "tablet", "earbuds", "smartwatch"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000005",
    name: "Nothing",
    slug: "nothing",
    logo: "/images/brands/nothing.png",
    description: "Innovative smartphones and audio products.",
    productCategories: ["mobile", "earbuds", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000006",
    name: "Xiaomi",
    slug: "xiaomi",
    logo: "/images/brands/xiaomi.png",
    description: "Smartphones and smart ecosystem products.",
    productCategories: ["mobile", "tablet", "smartwatch", "television", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000007",
    name: "Motorola",
    slug: "motorola",
    logo: "/images/brands/motorola.png",
    description: "Android smartphones and accessories.",
    productCategories: ["mobile", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000008",
    name: "iQOO",
    slug: "iqoo",
    logo: "/images/brands/iqoo.png",
    description: "Performance-oriented smartphones.",
    productCategories: ["mobile"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000009",
    name: "Realme",
    slug: "realme",
    logo: "/images/brands/realme.png",
    description: "Affordable smartphones and accessories.",
    productCategories: ["mobile", "earbuds", "smartwatch", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000000a",
    name: "OPPO",
    slug: "oppo",
    logo: "/images/brands/oppo.png",
    description: "Premium Android smartphones.",
    productCategories: ["mobile", "earbuds", "smartwatch"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000000b",
    name: "vivo",
    slug: "vivo",
    logo: "/images/brands/vivo.png",
    description: "Smartphones with advanced camera technology.",
    productCategories: ["mobile"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000000c",
    name: "Dell",
    slug: "dell",
    logo: "/images/brands/dell.png",
    description: "Computers, laptops and enterprise solutions.",
    productCategories: ["laptop", "desktop", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000000d",
    name: "HP",
    slug: "hp",
    logo: "/images/brands/hp.png",
    description: "Laptops, desktops and printers.",
    productCategories: ["laptop", "desktop", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000000e",
    name: "Lenovo",
    slug: "lenovo",
    logo: "/images/brands/lenovo.png",
    description: "Consumer and business computing devices.",
    productCategories: ["laptop", "desktop", "tablet", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000000f",
    name: "ASUS",
    slug: "asus",
    logo: "/images/brands/asus.png",
    description: "Gaming laptops and PC hardware.",
    productCategories: ["laptop", "desktop", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000010",
    name: "Acer",
    slug: "acer",
    logo: "/images/brands/acer.png",
    description: "Affordable laptops and gaming products.",
    productCategories: ["laptop", "desktop"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000011",
    name: "MSI",
    slug: "msi",
    logo: "/images/brands/msi.png",
    description: "Gaming laptops and PC components.",
    productCategories: ["laptop", "desktop", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000012",
    name: "Microsoft",
    slug: "microsoft",
    logo: "/images/brands/microsoft.png",
    description: "Surface devices and software.",
    productCategories: ["laptop", "tablet", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000013",
    name: "LG",
    slug: "lg",
    logo: "/images/brands/lg.png",
    description: "Electronics, displays and laptops.",
    productCategories: ["television", "laptop", "monitor"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000014",
    name: "Logitech",
    slug: "logitech",
    logo: "/images/brands/logitech.png",
    description: "Computer peripherals and accessories.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000015",
    name: "Keychron",
    slug: "keychron",
    logo: "/images/brands/keychron.png",
    description: "Mechanical keyboards for professionals.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000016",
    name: "Razer",
    slug: "razer",
    logo: "/images/brands/razer.png",
    description: "Gaming peripherals and accessories.",
    productCategories: ["laptop", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000017",
    name: "HyperX",
    slug: "hyperx",
    logo: "/images/brands/hyperx.png",
    description: "Gaming headsets and accessories.",
    productCategories: ["headphones", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000018",
    name: "TP-Link",
    slug: "tp-link",
    logo: "/images/brands/tp-link.png",
    description: "Networking products and accessories.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "688000000000000000000019",
    name: "SanDisk",
    slug: "sandisk",
    logo: "/images/brands/sandisk.png",
    description: "Storage and flash memory solutions.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000001a",
    name: "Seagate",
    slug: "seagate",
    logo: "/images/brands/seagate.png",
    description: "Hard drives and storage devices.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000001b",
    name: "Anker",
    slug: "anker",
    logo: "/images/brands/anker.png",
    description: "Charging and connectivity accessories.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000001c",
    name: "Belkin",
    slug: "belkin",
    logo: "/images/brands/belkin.png",
    description: "Premium accessories and adapters.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000001d",
    name: "Cooler Master",
    slug: "cooler-master",
    logo: "/images/brands/cooler-master.png",
    description: "PC cooling and gaming accessories.",
    productCategories: ["desktop", "accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000001e",
    name: "APC",
    slug: "apc",
    logo: "/images/brands/apc.png",
    description: "Power backup and UPS solutions.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "68800000000000000000001f",
    name: "Amazon Basics",
    slug: "amazon-basics",
    logo: "/images/brands/amazon-basics.png",
    description: "Affordable everyday electronics accessories.",
    productCategories: ["accessories"],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const products = [
  {
    _id: "686f8d9b7a2c4e1f3b5d9a01",
    name: "iPhone 16",
    slug: "iphone-16",
    category: "mobile", // Mobile
    brand: "Apple",
    shortDescription: "Latest Apple iPhone powered by A18 chip.",
    description:
      "The iPhone 16 delivers flagship performance, an advanced dual-camera system, and an all-day battery life.",
    price: 79999,
    originalPrice: 84999,
    discount: 6,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.8,
    totalReviews: 2456,
    stock: 34,
    specifications: {
      ram: "8GB",
      storage: "128GB",
      color: "Black",
    },
    tags: ["apple", "iphone", "mobile"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9a02",
    name: "iPhone 16 Pro",
    slug: "iphone-16-pro",
    category: "mobile",
    brand: "Apple",
    shortDescription: "Premium iPhone with Pro camera system.",
    description:
      "Built with titanium, featuring the A18 Pro chip and a professional-grade camera.",
    price: 119999,
    originalPrice: 129999,
    discount: 8,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.9,
    totalReviews: 1894,
    stock: 19,
    specifications: {
      ram: "8GB",
      storage: "256GB",
      color: "Natural Titanium",
    },
    tags: ["apple", "iphone", "pro"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9a03",
    name: "Samsung Galaxy S25",
    slug: "samsung-galaxy-s25",
    category: "mobile",
    brand: "Samsung",
    shortDescription: "Flagship Android smartphone.",
    description:
      "Galaxy S25 combines AI features, a vibrant AMOLED display, and premium cameras.",
    price: 74999,
    originalPrice: 82999,
    discount: 10,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.8,
    totalReviews: 1520,
    stock: 42,
    specifications: {
      ram: "12GB",
      storage: "256GB",
      color: "Silver Shadow",
    },
    tags: ["samsung", "android"],
    isFeatured: true,
    isTrending: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9a04",
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    category: "mobile",
    brand: "Samsung",
    shortDescription: "Ultra-premium flagship phone.",
    description:
      "The Galaxy S25 Ultra offers S Pen support, advanced AI, and exceptional photography.",
    price: 129999,
    originalPrice: 139999,
    discount: 7,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.9,
    totalReviews: 2311,
    stock: 16,
    specifications: {
      ram: "12GB",
      storage: "512GB",
      color: "Titanium Gray",
    },
    tags: ["samsung", "ultra"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9a05",
    name: "Google Pixel 9",
    slug: "google-pixel-9",
    category: "mobile",
    brand: "Google",
    shortDescription: "Google AI-powered smartphone.",
    description:
      "Pixel 9 offers an outstanding camera, pure Android experience, and Google AI features.",
    price: 69999,
    originalPrice: 74999,
    discount: 7,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.8,
    totalReviews: 945,
    stock: 28,
    specifications: {
      ram: "12GB",
      storage: "128GB",
      color: "Obsidian",
    },
    tags: ["google", "pixel"],
    isFeatured: false,
    isTrending: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9b01",
    name: 'MacBook Air 13" M4',
    slug: "macbook-air-13-m4",
    category: "laptop", // Laptop
    brand: "Apple",
    shortDescription: "Thin and lightweight Apple laptop.",
    description:
      "Powered by the Apple M4 chip with excellent battery life and Liquid Retina display.",
    price: 114900,
    originalPrice: 119900,
    discount: 4,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.9,
    totalReviews: 2431,
    stock: 15,
    specifications: {
      processor: "Apple M4",
      ram: "16GB",
      storage: "512GB SSD",
      display: '13.6" Liquid Retina',
    },
    tags: ["apple", "laptop"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9b02",
    name: 'MacBook Pro 14" M4 Pro',
    slug: "macbook-pro-14-m4-pro",
    category: "laptop",
    brand: "Apple",
    shortDescription: "Professional laptop for creators.",
    description:
      "High-performance MacBook Pro with Apple M4 Pro chip and Liquid Retina XDR display.",
    price: 199900,
    originalPrice: 209900,
    discount: 5,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.9,
    totalReviews: 1804,
    stock: 9,
    specifications: {
      processor: "Apple M4 Pro",
      ram: "24GB",
      storage: "1TB SSD",
      display: '14.2" Liquid Retina XDR',
    },
    tags: ["macbook", "pro"],
    isFeatured: true,
    isTrending: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9b03",
    name: "Dell XPS 13",
    slug: "dell-xps-13",
    category: "laptop",
    brand: "Dell",
    shortDescription: "Premium Windows ultrabook.",
    description:
      "Dell XPS 13 features Intel Core Ultra processor and stunning OLED display.",
    price: 149999,
    originalPrice: 159999,
    discount: 6,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.8,
    totalReviews: 1125,
    stock: 12,
    specifications: {
      processor: "Intel Core Ultra 7",
      ram: "16GB",
      storage: "512GB SSD",
      display: '13.4" OLED',
    },
    tags: ["dell", "xps"],
    isFeatured: false,
    isTrending: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9c01",
    name: "MX Master 3S Wireless Mouse",
    slug: "mx-master-3s-wireless-mouse",
    category: "mouse", // Mouse
    brand: "Logitech",
    shortDescription: "Premium wireless productivity mouse.",
    description:
      "Designed for professionals with MagSpeed scrolling and ergonomic comfort.",
    price: 8995,
    originalPrice: 10995,
    discount: 18,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.9,
    totalReviews: 3245,
    stock: 58,
    specifications: {
      connectivity: "Bluetooth + USB Receiver",
      color: "Graphite",
    },
    tags: ["mouse", "logitech"],
    isFeatured: false,
    isTrending: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "686f8d9b7a2c4e1f3b5d9c02",
    name: "MX Keys S Wireless Keyboard",
    slug: "mx-keys-s-wireless-keyboard",
    category: "keyboard", // Keyboard
    brand: "Logitech",
    shortDescription: "Wireless backlit productivity keyboard.",
    description:
      "Premium keyboard with smart illumination and multi-device connectivity.",
    price: 10995,
    originalPrice: 12995,
    discount: 15,
    thumbnail:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80",
    ],
    rating: 4.8,
    totalReviews: 1842,
    stock: 31,
    specifications: {
      connectivity: "Bluetooth",
    },
    tags: ["keyboard", "logitech"],
    isFeatured: false,
    isTrending: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const heroSlides = [
  {
    id: 1,
    tagline: "Best Deal Online on smart watches",
    title: "SMART WEARABLE.",
    subtitle: "UP to 80% OFF",
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=400&fit=crop",
    bg: "from-slate-900 via-slate-800 to-black",
  },
  {
    id: 2,
    tagline: "Best Deal Online on smartphones",
    title: "LATEST PHONES.",
    subtitle: "UP to 60% OFF",
    image:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&h=400&fit=crop",
    bg: "from-purple-900 via-fuchsia-800 to-pink-700",
  },
  {
    id: 3,
    tagline: "Best Deal Online on electronics",
    title: "TOP GADGETS.",
    subtitle: "UP to 70% OFF",
    image:
      "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500&h=400&fit=crop",
    bg: "from-sky-900 via-cyan-700 to-blue-600",
  },
];

// const categoryOffersMap: Record<string, IProductOffer[]> = {
//   mobile: [
//     {
//       id: "offer-1",
//       eventLabel: "Mobiles MAHOTSAV",
//       title: "POVA Curve 2 5G",
//       price: 28499,
//       originalPrice: 31999,
//       tagline: "World's Slimmest 8000mAh Curve Dis.",
//       emiAmount: 4750,
//       rating: 4.3,
//       image:
//         "https://rukminim1.flixcart.com/image/312/312/xif0q/mobile/3/6/8/-original-imahf6vhzg9tzfzr.jpeg?q=70",
//       bg: "from-slate-800 via-slate-700 to-slate-900",
//     },
//     {
//       id: "offer-2",
//       eventLabel: "Mobiles MAHOTSAV",
//       title: "motorola g96 5G",
//       price: 15999,
//       originalPrice: 25999,
//       tagline: "Segment's Biggest 6000mAh Battery",
//       emiAmount: 2667,
//       rating: 4.4,
//       image:
//         "https://rukminim1.flixcart.com/image/312/312/xif0q/mobile/k/2/6/-original-imah8f6yq8q8q8q8.jpeg?q=70",
//       bg: "from-rose-900 via-rose-800 to-rose-950",
//     },
//     {
//       id: "offer-3",
//       eventLabel: "Mobiles MAHOTSAV",
//       title: "Galaxy S25 Ultra 512GB",
//       price: 84999,
//       originalPrice: 129999,
//       tagline: "Galaxy AI is here",
//       emiAmount: 14167,
//       rating: 4.6,
//       image:
//         "https://rukminim1.flixcart.com/image/312/312/xif0q/mobile/5/4/3/-original-imah8yq8q8q8q8q8.jpeg?q=70",
//       bg: "from-indigo-950 via-indigo-900 to-slate-900",
//     },
//   ],
//   laptop: [
//     {
//       id: "laptop-offer-1",
//       eventLabel: "Laptop Fest",
//       title: "MacBook Air M4",
//       price: 114900,
//       originalPrice: 119900,
//       tagline: "Supercharged by Apple M4 chip",
//       emiAmount: 9583,
//       rating: 4.9,
//       image: "/images/products/macbook-air-m4.png",
//       bg: "from-gray-800 via-gray-700 to-gray-900",
//     },
//     {
//       id: "laptop-offer-2",
//       eventLabel: "Laptop Fest",
//       title: "ROG Zephyrus G16",
//       price: 219999,
//       originalPrice: 229999,
//       tagline: "Gaming powerhouse with OLED display",
//       emiAmount: 18333,
//       rating: 4.8,
//       image: "/images/products/rog-zephyrus-g16.png",
//       bg: "from-zinc-900 via-zinc-800 to-black",
//     },
//   ],
// };

// export function getOffersByCategory(categoryId: string): IProductOffer[] {
//   return categoryOffersMap[categoryId] ?? [];
// }
