import { productMedia } from "./seed-images";

const now = () => ({ createdAt: new Date(), updatedAt: new Date() });

function media(slug: string) {
  const m = productMedia[slug];
  if (!m) {
    throw new Error(`Missing product media for slug: ${slug}`);
  }
  return m;
}

/** Extra products so every category has ≥2 items (base products come from lib/data) */
export const extraProducts = [
  {
    _id: "686f8d9b7a2c4e1f3b5d9c03",
    name: "Logitech G Pro X Superlight 2",
    slug: "logitech-g-pro-x-superlight-2",
    category: "mouse",
    brand: "Logitech",
    shortDescription: "Ultra-lightweight wireless gaming mouse.",
    description:
      "Pro-grade sensor and featherweight build for competitive gaming.",
    price: 14995,
    originalPrice: 16995,
    discount: 12,
    ...media("logitech-g-pro-x-superlight-2"),
    rating: 4.8,
    totalReviews: 2104,
    stock: 40,
    specifications: { connectivity: "LIGHTSPEED Wireless", weight: "60g" },
    tags: ["mouse", "gaming", "logitech"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5d9c04",
    name: "Keychron K2 V2",
    slug: "keychron-k2-v2",
    category: "keyboards",
    brand: "Keychron",
    shortDescription: "Compact wireless mechanical keyboard.",
    description:
      "Hot-swappable mechanical keyboard with RGB backlight and Mac/Windows layout.",
    price: 8999,
    originalPrice: 10999,
    discount: 18,
    ...media("keychron-k2-v2"),
    rating: 4.7,
    totalReviews: 1560,
    stock: 45,
    specifications: { switches: "Gateron Brown", connectivity: "Bluetooth / Wired" },
    tags: ["keyboard", "mechanical", "keychron"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5d9d01",
    name: "iPad Air M2",
    slug: "ipad-air-m2",
    category: "tablet",
    brand: "Apple",
    shortDescription: "Powerful everyday Apple tablet.",
    description:
      "iPad Air with M2 chip, Liquid Retina display, and all-day battery life.",
    price: 59900,
    originalPrice: 64900,
    discount: 8,
    ...media("ipad-air-m2"),
    rating: 4.8,
    totalReviews: 1320,
    stock: 22,
    specifications: { storage: "128GB", display: '11" Liquid Retina' },
    tags: ["tablet", "apple", "ipad"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5d9d02",
    name: "Samsung Galaxy Tab S9",
    slug: "samsung-galaxy-tab-s9",
    category: "tablet",
    brand: "Samsung",
    shortDescription: "Premium Android tablet with S Pen.",
    description:
      "AMOLED display, Snapdragon performance, and included S Pen for creativity.",
    price: 72999,
    originalPrice: 79999,
    discount: 9,
    ...media("samsung-galaxy-tab-s9"),
    rating: 4.7,
    totalReviews: 980,
    stock: 18,
    specifications: { storage: "256GB", display: '11" Dynamic AMOLED' },
    tags: ["tablet", "samsung"],
    isFeatured: true,
    isTrending: false,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5d9e01",
    name: "Dell OptiPlex Tower",
    slug: "dell-optiplex-tower",
    category: "desktop",
    brand: "Dell",
    shortDescription: "Reliable business desktop PC.",
    description:
      "Compact tower with Intel Core processor, ideal for office and home work.",
    price: 54999,
    originalPrice: 59999,
    discount: 8,
    ...media("dell-optiplex-tower"),
    rating: 4.5,
    totalReviews: 640,
    stock: 14,
    specifications: { processor: "Intel Core i5", ram: "16GB", storage: "512GB SSD" },
    tags: ["desktop", "dell"],
    isFeatured: false,
    isTrending: false,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5d9e02",
    name: "HP Pavilion Desktop",
    slug: "hp-pavilion-desktop",
    category: "desktop",
    brand: "HP",
    shortDescription: "Everyday home desktop computer.",
    description:
      "Balanced performance for streaming, browsing, and light creative work.",
    price: 47999,
    originalPrice: 52999,
    discount: 9,
    ...media("hp-pavilion-desktop"),
    rating: 4.4,
    totalReviews: 512,
    stock: 20,
    specifications: { processor: "AMD Ryzen 5", ram: "16GB", storage: "1TB SSD" },
    tags: ["desktop", "hp"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5d9f01",
    name: "Apple Watch Series 10",
    slug: "apple-watch-series-10",
    category: "smartwatch",
    brand: "Apple",
    shortDescription: "Advanced health and fitness smartwatch.",
    description:
      "Brighter display, deeper health insights, and seamless iPhone integration.",
    price: 46900,
    originalPrice: 49900,
    discount: 6,
    ...media("apple-watch-series-10"),
    rating: 4.8,
    totalReviews: 2890,
    stock: 35,
    specifications: { size: "42mm", connectivity: "GPS + Cellular" },
    tags: ["smartwatch", "apple"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5d9f02",
    name: "Samsung Galaxy Watch 7",
    slug: "samsung-galaxy-watch-7",
    category: "smartwatch",
    brand: "Samsung",
    shortDescription: "AI-powered Android smartwatch.",
    description:
      "Track sleep, workouts, and wellness with a vibrant circular AMOLED display.",
    price: 32999,
    originalPrice: 36999,
    discount: 11,
    ...media("samsung-galaxy-watch-7"),
    rating: 4.6,
    totalReviews: 1540,
    stock: 28,
    specifications: { size: "44mm", connectivity: "Bluetooth / LTE" },
    tags: ["smartwatch", "samsung"],
    isFeatured: true,
    isTrending: false,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da001",
    name: "Sony WH-1000XM5",
    slug: "sony-wh-1000xm5",
    category: "headphones",
    brand: "Sony",
    shortDescription: "Industry-leading noise cancelling headphones.",
    description:
      "Premium over-ear headphones with adaptive ANC and 30-hour battery life.",
    price: 29990,
    originalPrice: 34990,
    discount: 14,
    ...media("sony-wh-1000xm5"),
    rating: 4.9,
    totalReviews: 4120,
    stock: 50,
    specifications: { type: "Over-ear", connectivity: "Bluetooth 5.2" },
    tags: ["headphones", "sony", "anc"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da002",
    name: "HyperX Cloud III",
    slug: "hyperx-cloud-iii",
    category: "headphones",
    brand: "HyperX",
    shortDescription: "Comfortable gaming headset.",
    description:
      "Dual chamber drivers, memory foam ear cups, and detachable noise-cancelling mic.",
    price: 9990,
    originalPrice: 11990,
    discount: 17,
    ...media("hyperx-cloud-iii"),
    rating: 4.7,
    totalReviews: 2210,
    stock: 60,
    specifications: { type: "Over-ear", connectivity: "3.5mm / USB" },
    tags: ["headphones", "gaming", "hyperx"],
    isFeatured: false,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da101",
    name: "Apple AirPods Pro 2",
    slug: "apple-airpods-pro-2",
    category: "earbuds",
    brand: "Apple",
    shortDescription: "Active noise cancelling true wireless earbuds.",
    description:
      "Adaptive Audio, Transparency mode, and MagSafe charging case.",
    price: 24900,
    originalPrice: 26900,
    discount: 7,
    ...media("apple-airpods-pro-2"),
    rating: 4.8,
    totalReviews: 5340,
    stock: 70,
    specifications: { chip: "H2", anc: "Yes" },
    tags: ["earbuds", "apple", "airpods"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da102",
    name: "Samsung Galaxy Buds3 Pro",
    slug: "samsung-galaxy-buds3-pro",
    category: "earbuds",
    brand: "Samsung",
    shortDescription: "Premium Galaxy AI earbuds.",
    description:
      "High-res audio, intelligent ANC, and seamless Galaxy device pairing.",
    price: 19999,
    originalPrice: 22999,
    discount: 13,
    ...media("samsung-galaxy-buds3-pro"),
    rating: 4.6,
    totalReviews: 1780,
    stock: 55,
    specifications: { anc: "Yes", connectivity: "Bluetooth 5.4" },
    tags: ["earbuds", "samsung"],
    isFeatured: true,
    isTrending: false,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da201",
    name: "Anker 737 Power Bank",
    slug: "anker-737-power-bank",
    category: "accessories",
    brand: "Anker",
    shortDescription: "140W portable charger for laptops and phones.",
    description:
      "High-capacity power bank with smart digital display and fast USB-C charging.",
    price: 12999,
    originalPrice: 14999,
    discount: 13,
    ...media("anker-737-power-bank"),
    rating: 4.7,
    totalReviews: 890,
    stock: 80,
    specifications: { capacity: "24000mAh", output: "140W" },
    tags: ["accessories", "anker", "charger"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da202",
    name: "Belkin MagSafe 3-in-1 Stand",
    slug: "belkin-magsafe-3-in-1-stand",
    category: "accessories",
    brand: "Belkin",
    shortDescription: "Charge iPhone, Watch, and AirPods together.",
    description:
      "Official MagSafe charging stand for a tidy desk or nightstand setup.",
    price: 14999,
    originalPrice: 16999,
    discount: 12,
    ...media("belkin-magsafe-3-in-1-stand"),
    rating: 4.5,
    totalReviews: 670,
    stock: 42,
    specifications: { compatibility: "MagSafe", ports: "USB-C" },
    tags: ["accessories", "belkin", "magsafe"],
    isFeatured: false,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da301",
    name: 'Samsung 55" QLED 4K TV',
    slug: "samsung-55-qled-4k-tv",
    category: "television",
    brand: "Samsung",
    shortDescription: "Vibrant QLED smart television.",
    description:
      "Quantum Dot color, 4K upscaling, and smart streaming apps built in.",
    price: 64990,
    originalPrice: 74990,
    discount: 13,
    ...media("samsung-55-qled-4k-tv"),
    rating: 4.7,
    totalReviews: 2010,
    stock: 16,
    specifications: { size: '55"', resolution: "4K UHD" },
    tags: ["television", "samsung", "qled"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da302",
    name: 'LG 65" OLED C4',
    slug: "lg-65-oled-c4",
    category: "television",
    brand: "LG",
    shortDescription: "Cinema-grade OLED smart TV.",
    description:
      "Perfect blacks, webOS smart platform, and gaming-ready HDMI 2.1 ports.",
    price: 189990,
    originalPrice: 219990,
    discount: 14,
    ...media("lg-65-oled-c4"),
    rating: 4.9,
    totalReviews: 1450,
    stock: 9,
    specifications: { size: '65"', resolution: "4K OLED" },
    tags: ["television", "lg", "oled"],
    isFeatured: true,
    isTrending: false,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da401",
    name: "Sony Alpha ZV-E10",
    slug: "sony-alpha-zv-e10",
    category: "cameras",
    brand: "Sony",
    shortDescription: "Vlogging mirrorless camera.",
    description:
      "APS-C sensor, flip screen, and product showcase setting for creators.",
    price: 69990,
    originalPrice: 76990,
    discount: 9,
    ...media("sony-alpha-zv-e10"),
    rating: 4.7,
    totalReviews: 1120,
    stock: 12,
    specifications: { sensor: "APS-C", video: "4K 30p" },
    tags: ["cameras", "sony", "mirrorless"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da402",
    name: "Canon EOS R50",
    slug: "canon-eos-r50",
    category: "cameras",
    brand: "Canon",
    shortDescription: "Compact mirrorless for beginners.",
    description:
      "Easy content creation tools with Dual Pixel AF and 4K video.",
    price: 74990,
    originalPrice: 81990,
    discount: 9,
    ...media("canon-eos-r50"),
    rating: 4.6,
    totalReviews: 860,
    stock: 15,
    specifications: { sensor: "APS-C", video: "4K 30p" },
    tags: ["cameras", "canon"],
    isFeatured: false,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da501",
    name: "JBL Flip 6",
    slug: "jbl-flip-6",
    category: "speakers",
    brand: "JBL",
    shortDescription: "Portable waterproof Bluetooth speaker.",
    description: "Bold sound, IP67 rating, and up to 12 hours of playtime.",
    price: 9999,
    originalPrice: 11999,
    discount: 17,
    ...media("jbl-flip-6"),
    rating: 4.7,
    totalReviews: 3200,
    stock: 90,
    specifications: { battery: "12 hours", waterproof: "IP67" },
    tags: ["speakers", "jbl", "portable"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da502",
    name: "Sony SRS-XB43",
    slug: "sony-srs-xb43",
    category: "speakers",
    brand: "Sony",
    shortDescription: "Extra bass party Bluetooth speaker.",
    description:
      "Deep bass, light effects, and durable design for indoor and outdoor use.",
    price: 14990,
    originalPrice: 17990,
    discount: 17,
    ...media("sony-srs-xb43"),
    rating: 4.6,
    totalReviews: 1455,
    stock: 38,
    specifications: { battery: "24 hours", waterproof: "IP67" },
    tags: ["speakers", "sony"],
    isFeatured: false,
    isTrending: false,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da601",
    name: "TP-Link Tapo C210",
    slug: "tp-link-tapo-c210",
    category: "cctv",
    brand: "TP-Link",
    shortDescription: "2K indoor pan/tilt security camera.",
    description:
      "Motion tracking, two-way audio, and night vision for home monitoring.",
    price: 2499,
    originalPrice: 3499,
    discount: 29,
    ...media("tp-link-tapo-c210"),
    rating: 4.5,
    totalReviews: 4100,
    stock: 120,
    specifications: { resolution: "2K", nightVision: "Yes" },
    tags: ["cctv", "tp-link", "security"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da602",
    name: "Hikvision ColorVu Dome",
    slug: "hikvision-colorvu-dome",
    category: "cctv",
    brand: "Hikvision",
    shortDescription: "Full-color outdoor dome camera.",
    description:
      "24/7 colorful imaging with built-in warm light for clearer night footage.",
    price: 5999,
    originalPrice: 7499,
    discount: 20,
    ...media("hikvision-colorvu-dome"),
    rating: 4.4,
    totalReviews: 980,
    stock: 65,
    specifications: { resolution: "1080p", nightVision: "ColorVu" },
    tags: ["cctv", "hikvision"],
    isFeatured: false,
    isTrending: false,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da701",
    name: "PlayStation 5 Slim",
    slug: "playstation-5-slim",
    category: "gaming",
    brand: "Sony",
    shortDescription: "Next-gen gaming console.",
    description:
      "Immersive 4K gaming with DualSense controller and ultra-fast SSD.",
    price: 54990,
    originalPrice: 54990,
    discount: 0,
    ...media("playstation-5-slim"),
    rating: 4.9,
    totalReviews: 6200,
    stock: 25,
    specifications: { storage: "1TB SSD", resolution: "4K" },
    tags: ["gaming", "playstation", "console"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da702",
    name: "Xbox Series X",
    slug: "xbox-series-x",
    category: "gaming",
    brand: "Microsoft",
    shortDescription: "Most powerful Xbox console.",
    description:
      "True 4K gaming at up to 120fps with Game Pass ready out of the box.",
    price: 52990,
    originalPrice: 54990,
    discount: 4,
    ...media("xbox-series-x"),
    rating: 4.8,
    totalReviews: 4800,
    stock: 20,
    specifications: { storage: "1TB SSD", resolution: "4K" },
    tags: ["gaming", "xbox", "console"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da801",
    name: 'LG UltraGear 27" 165Hz',
    slug: "lg-ultragear-27-165hz",
    category: "monitors",
    brand: "LG",
    shortDescription: "Fast IPS gaming monitor.",
    description:
      "QHD resolution, 1ms response, and AMD FreeSync for smooth gameplay.",
    price: 24999,
    originalPrice: 29999,
    discount: 17,
    ...media("lg-ultragear-27-165hz"),
    rating: 4.7,
    totalReviews: 1890,
    stock: 30,
    specifications: { size: '27"', refreshRate: "165Hz", resolution: "2560x1440" },
    tags: ["monitors", "lg", "gaming"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da802",
    name: 'Dell UltraSharp 27" 4K',
    slug: "dell-ultrasharp-27-4k",
    category: "monitors",
    brand: "Dell",
    shortDescription: "Color-accurate productivity monitor.",
    description:
      "Factory-calibrated 4K IPS panel for design, editing, and office work.",
    price: 42999,
    originalPrice: 47999,
    discount: 10,
    ...media("dell-ultrasharp-27-4k"),
    rating: 4.8,
    totalReviews: 980,
    stock: 18,
    specifications: { size: '27"', resolution: "3840x2160", panel: "IPS" },
    tags: ["monitors", "dell", "4k"],
    isFeatured: true,
    isTrending: false,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da901",
    name: "Samsung 990 PRO 2TB NVMe",
    slug: "samsung-990-pro-2tb",
    category: "storage",
    brand: "Samsung",
    shortDescription: "Ultra-fast PCIe 4.0 SSD.",
    description:
      "Blazing sequential speeds for gaming, content creation, and heavy workloads.",
    price: 18999,
    originalPrice: 22999,
    discount: 17,
    ...media("samsung-990-pro-2tb"),
    rating: 4.9,
    totalReviews: 2540,
    stock: 75,
    specifications: { capacity: "2TB", interface: "PCIe 4.0 NVMe" },
    tags: ["storage", "ssd", "samsung"],
    isFeatured: true,
    isTrending: true,
    isActive: true,
    ...now(),
  },
  {
    _id: "686f8d9b7a2c4e1f3b5da902",
    name: "Seagate Expansion 4TB HDD",
    slug: "seagate-expansion-4tb",
    category: "storage",
    brand: "Seagate",
    shortDescription: "Portable external hard drive.",
    description:
      "Plug-and-play USB storage for backups, media libraries, and file archives.",
    price: 8499,
    originalPrice: 9999,
    discount: 15,
    ...media("seagate-expansion-4tb"),
    rating: 4.5,
    totalReviews: 3120,
    stock: 100,
    specifications: { capacity: "4TB", interface: "USB 3.0" },
    tags: ["storage", "hdd", "seagate"],
    isFeatured: false,
    isTrending: true,
    isActive: true,
    ...now(),
  },
];
